/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  set_admin: SetAdminArgs;
} | {
  set_latest_answer: SetLatestAnswerArgs;
};
export type Uint128 = string;
export interface SetAdminArgs {
  admin?: string | null;
  value: boolean;
}
export interface SetLatestAnswerArgs {
  answer: Answer;
}
export interface Answer {
  positive: boolean;
  value: Uint128;
}
export type QueryMsg = {
  latest_round: LatestRoundMsg;
} | {
  latest_answer: LatestAnswerMsg;
} | {
  round_data: RoundDataMsg;
};
export type LatestRoundMsg = null;
export type LatestAnswerMsg = null;
export interface RoundDataMsg {
  round_id: Uint128;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface GetRoundDataResult {
  answer: Answer;
  answered_in_round: Uint128;
  round_id: Uint128;
  started_at: Timestamp;
  updated_at: Timestamp;
}