/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin?: string | null;
}
export type ExecuteMsg = {
  set_admin: SetAdminExec;
};
export type Addr = string;
export interface SetAdminExec {
  admin: Addr;
}
export type QueryMsg = {
  price: PriceQuery;
};
export interface PriceQuery {}
export interface MigrateMsg {}
export type Uint128 = string;