/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin?: string | null;
  reward_token: string;
  reward_tracker: string;
}
export type ExecuteMsg = {
  set_admin: SetAdminExec;
} | {
  update_last_distribution_time: UpdateLastDistributionTimeExec;
} | {
  set_tokens_per_interval: SetTokensPerIntervalExec;
} | {
  distribute: DistributeExec;
};
export type Uint128 = string;
export interface SetAdminExec {
  admin: string;
}
export interface UpdateLastDistributionTimeExec {}
export interface SetTokensPerIntervalExec {
  amount: Uint128;
}
export interface DistributeExec {}
export type QueryMsg = {
  admin: AdminQuery;
} | {
  reward_token: RewardTokenQuery;
} | {
  token_per_interval: TokenPerIntervalQuery;
} | {
  pending_rewards: PendingRewardsQuery;
};
export interface AdminQuery {}
export interface RewardTokenQuery {}
export interface TokenPerIntervalQuery {}
export interface PendingRewardsQuery {}
export interface MigrateMsg {}
export type Addr = string;