/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin?: string | null;
  token0: string;
  token1: string;
}
export type ExecuteMsg = {
  set_reserves: {
    reserves0: Uint128;
    reserves1: Uint128;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  reserves: {};
};
export interface MigrateMsg {}
export type TupleOfUint128AndUint128 = [Uint128, Uint128];