/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin?: string | null;
  vault: string;
}
export type ExecuteMsg = {
  set_admin: SetAdminExec;
} | {
  set_handler: SetHandlerExec;
} | {
  set_is_global_short_data_ready: SetIsGlobalShortDataReadyExec;
} | {
  update_global_short_data: UpdateGlobalShortDataExec;
};
export type Addr = string;
export type Uint128 = string;
export interface SetAdminExec {
  admin: Addr;
}
export interface SetHandlerExec {
  account: Addr;
  is_handler: boolean;
}
export interface SetIsGlobalShortDataReadyExec {
  value: boolean;
}
export interface UpdateGlobalShortDataExec {
  account: string;
  collateral_token: string;
  index_token: string;
  is_increase: boolean;
  is_long: boolean;
  mark_price: Uint128;
  size_delta: Uint128;
}
export type QueryMsg = {
  next_global_short_data: NextGlobalShortDataQuery;
} | {
  global_short_average_prices: GlobalShortAveragePricesQuery;
} | {
  global_short_delta: GlobalShortDeltaQuery;
} | {
  is_global_short_data_ready: IsGlobalShortDataReadyQuery;
} | {
  realised_pnl: RealisedPnlQuery;
};
export interface NextGlobalShortDataQuery {
  account: string;
  collateral_token: string;
  index_token: string;
  is_increase: boolean;
  next_price: Uint128;
  size_delta: Uint128;
}
export interface GlobalShortAveragePricesQuery {
  token: string;
}
export interface GlobalShortDeltaQuery {
  token: string;
}
export interface IsGlobalShortDataReadyQuery {}
export interface RealisedPnlQuery {
  account: string;
  collateral_token: string;
  index_token: string;
  is_increase: boolean;
  next_price: Uint128;
  size_delta: Uint128;
}
export interface MigrateMsg {}
export type TupleOfBooleanAndUint128 = [boolean, Uint128];
export type Boolean = boolean;
export type TupleOfUint128AndUint128 = [Uint128, Uint128];
export type Int128 = number;