name: Publish Package to npmjs
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm config set _authToken=${{ secrets.NPM_TOKEN }}
      - run: npm config fix
      - run: npm publish
